# This is a document with key attributes of current team members

title = "Team registry"

[litvintech]
name = "Valery Litvin"
gitcoin = "0xf103D2db8024F4B885433ADAF72032Ac58304e03"
payouts = "0x00cFF8CF7Bff03A9A2a81c01920ffD8cFa7AE9D0"
github = "litvintech"
telegram = "litvintech"
keybase = "litvintech"
ipfs = "QmXkd1HZKCy5oTdCDPTiU8kzh3kz79AeLmchCQLXetAJvH"
cyber = "cyber1s3748ghvcwvrws3kxsdc8xnan3qhv777tg4yv2"

[xhipster]
name = "Dima Starodubcev"
gitcoin = "0x7C4401aE98F12eF6de39aE24cf9fc51f80EBa16B"
payouts = "0x7C4401aE98F12eF6de39aE24cf9fc51f80EBa16B"
github = "xhipster"
telegram = "xhipster"
keybase = "21xhipster"
ipfs = "QmV9P23ZC2GCsDanZwZQHWEKdnd2VyXwzgM5x7XA7iMgnp"
cyber = "cyber1hlu0kqwvxmhjjsezr00jdrvs2k537mqhatjadg"

[savetheales]
name = "Ales Puchilo"
gitcoin = "0x00466845B9906578ac86cBA4C2Dda0F2c46461F6"
payouts = "0x00CA47db1BE92C1072e973fd8DC4A082f7d70214"
github = "SaveTheAles"
telegram = "savetheales"
keybase = "savetheales"
ipfs = "QmTL3gftAjBZ7WU4GppYg7odQymraN66VFk1NkQyEbbBNj"
cyber = "cyber1hmkqhy8ygl6tnl5g8tc503rwrmmrkjcq4878e0"

[dimakorzhovnik]
name = "Dima Korzhovnik"
gitcoin = "0xE8298160C9E8cabd8F2711B92529E0aFE8FB01FB"
payouts = "0xE8298160C9E8cabd8F2711B92529E0aFE8FB01FB"
github = "dimakorzhovnik"
telegram = "korzhovnik_dima"
keybase = "dimakorzhovnik"
ipfs = "QmciKaXo9bSF3BsV2JLponqmrWqbvGiw5qEG6epQsRKFTA"
cyber = "cyber177gvvqtn7xl8qvl6yw4vax9raz80fx66aukc94"

[serejandmyself]
name = "Sergey Simanovsky"
gitcoin = "0x4fd54cd3c329113e0759b52A666Ba2ac1bF4f917"
payouts = "0x8B5b28646ADa61d647Fe307b474EEb38532ea714"
github = "serejandmyself"
telegram = "serejandmyself"
keybase = "serejandmyself"
ipfs = "QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv"
cyber = "cyber1f7nx65pmayfenpfwzwaamwas4ygmvalqwcexna"
