version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.50
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: |
          cd site
          HUGO_ENV=production hugo -v -s src/
      - run:
          name: "Test Website"
          command: |
          cd site
          htmlproofer src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
