# This is a document with key attributes of current team members

title = "Team registry"

[litvintech]
name = "Valery Litvin"
ethereum = "0x00cFF8CF7Bff03A9A2a81c01920ffD8cFa7AE9D0"
bostrom = ""
cyber = "cyber1s3748ghvcwvrws3kxsdc8xnan3qhv777tg4yv2"
github = "litvintech"
telegram = "litvintech"

[xhipster]
name = "Master Cyb"
ethereum = "0x7C4401aE98F12eF6de39aE24cf9fc51f80EBa16B"
bostrom = "bostrom1qn8sr2hzmktlecusdtxj9hwj0upnm0jft9snar"
cyber = "cyber1hlu0kqwvxmhjjsezr00jdrvs2k537mqhatjadg"
github = "mastercyb"
telegram = "mastercyb"

[savetheales]
name = "Ales Puchilo"
ethereum = "0x00CA47db1BE92C1072e973fd8DC4A082f7d70214"
bostrom = "bostrom1hmkqhy8ygl6tnl5g8tc503rwrmmrkjcq3lduwj"
cyber = "cyber1hmkqhy8ygl6tnl5g8tc503rwrmmrkjcq4878e0"
github = "SaveTheAles"
telegram = "savetheales"

[dimakorzhovnik]
name = "Dima Korzhovnik"
ethereum = "0xE8298160C9E8cabd8F2711B92529E0aFE8FB01FB"
bostrom = ""
cyber = "cyber16macu2qtc0jmqc7txvf0wkz84cycsx72r9y539"
github = "dimakorzhovnik"
telegram = "korzhovnik_dima"

[mrlp4]
name = "Kirill Laptanovich"
ethereum = "0x3a9D2CC504F6d937AdA7f8c8C39BD8D047623584"
bostrom = ""
cyber = "cyber1t0hmc79ht0qja92p6qgxn3ee3a3rzqutgxcvhw"
github = "mrlp4"
telegram = "mrlp4"

[serejandmyself]
name = "Sergey Simanovsky"
ethereum = "0x8B5b28646ADa61d647Fe307b474EEb38532ea714"
bostrom = ""
cyber = "cyber1f7nx65pmayfenpfwzwaamwas4ygmvalqwcexna"
github = "serejandmyself"
telegram = "serejandmyself"
urbit id = "~dilled-fastyd"

[nesqchay]
name = "Konstantin Koliadin"
ethereum = "0x4a58362D60E81bB5596c546881312c820aBb5eda"
bostrom = ""
cyber = "cyber1aqpjltra43vujfp6eqy34vm6xccgf5uavgtvm5"
github = "nesqchay"
telegram = "nesqchay"

[EI_NIVVO]
name = "Stepan Bersin"
ethereum = "0x81645C8072a592c17f3D8424D74B04bFa0cF299e"
bostrom = ""
cyber = "cyber1ay267fakkrgfy9lf2m7wsj8uez2dgylh0w7jjt"
github = "EI-NIVVO"
telegram = "EI_NIVVO"

[CyberPimp420]
name = "Ana Vidovic"
ethereum = "0xBccd16754fBC894883e836AEa854FF63BBAe9884e"
bostrom = ""
cyber = ""
github = "AnaGlorija"
telegram = "CyberPimp420"
